pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'M3'
    }

    environment {
        DOCKERHUB_CRED = credentials('dockerhub-credentials')
    }

    stages {
        stage('Git Clone') {
            // Github에서 소스코드 가져오기
            steps {
                echo 'Git Clone'
                git url: 'https://github.com/fla246/spring-petclinic.git',
                branch: 'main'
            }
        }

        // Maven으로 Build 
        stage('Maven Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'
            
            }
        }
        // Docker 이미지 생성
        stage('Docker Build') {
            steps {
                sh 'docker build -t penguin-spring:${BUILD_NUMBER} .'
                sh 'docker tag penguin-spring:${BUILD_NUMBER} yerimy/penguin-spring:${BUILD_NUMBER}'
            }
        }
        // Docker 이미지를 Docker Hub로 Push
        stage('Docker Push') {
            steps {
                sh 'echo ${DOCKERHUB_CRED_PSW} | docker login -u ${DOCKERHUB_CRED_USR} --password-stdin'
                sh 'docker push yerimy/penguin-spring:${BUILD_NUMBER}'
            }
        }

        // Docker Hub를 이용한 배포
        stage('k8s Deploy') {
            steps {
                sh """
                    sed -i "s|yerimy/penguin-spring:.*|yerimy/penguin-spring:${BUILD_NUMBER}|g" k8s/petclinic-deploy.yaml
                    kubectl apply -f k8s/petclinic-ingress.yaml
                    kubectl apply -f k8s/petclinic-deploy.yaml
                    kubectl apply -f k8s/petclinic-service.yaml
                    """
                }
        }

        
        // Docker 이미지 삭제
        stage('Docker Clean') {
            steps {
                sh '''
                docker rmi penguin-spring:${BUILD_NUMBER}
                docker rmi yerimy/penguin-spring:${BUILD_NUMBER}
                '''
            }
        }

    }
}

